image: continuumio/miniconda3

before_script:
  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda config --add channels r
  - conda config --add channels bioconda
#  - conda install snakemake
  - git clone https://bitbucket.org/snakemake/snakemake.git
  - cd snakemake
  - git checkout ct-ftp-close-every-time-option
  - conda env create -f environment.yml -n snakemake-testing
  - pip install -e .
  - source activate snakemake-testing
  - pip install PyYAML
  - cd ..

stages:
    - rulegraph
    - run
    
# DAG
#rulegraph:
#  stage: rulegraph
#  script: 
#    - snakemake --configfile tests/config.remote.yaml --rulegraph --use-conda

run:
  stage: run
  script:
    - source activate snakemake-testing
#    - python conf.py
    - snakemake --configfile tests/config.remote.yaml --use-conda -j 8
