image: continuumio/miniconda3

before_script:
  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda config --add channels r
  - conda config --add channels bioconda
#  - conda install snakemake
  - git clone https://bitbucket.org/snakemake/snakemake.git
  - cd snakemake
  - git checkout ct-ftp-close-every-time-option
  - virtualenv -p python3 .venv
  - source .venv/bin/activate
  - python setup.py install
  - cd ..

stages:
    - rulegraph
    - run
    
# DAG
#rulegraph:
#  stage: rulegraph
#  script: 
#    - snakemake --configfile tests/config.remote.yaml --rulegraph --use-conda

run:
  stage: run
  script:
    - python conf.py
    - snakemake --use-conda -j 8
