image: continuumio/miniconda3

before_script:
  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda config --add channels r
  - conda config --add channels bioconda
  - conda install snakemake click

stages:
    - rulegraph
    - run
    - sina
    
# DAG
#rulegraph:
#  stage: rulegraph
#  script: 
#    - snakemake --configfile tests/config.remote.yaml --rulegraph --use-conda

run:
  stage: run
  script:
    - python conf.py --project test --remote PRJEB14409 --clustering usearch_smallmem --classification stampa --forward_primer CCTACGGGNGGCWGCAG --reverse_primer GACTACHVGGGTATCTAATCC --mergepairs vsearch --reference_db silva
    - snakemake  --use-conda -j 8

sina:
  stage: sina
  script:
    - python conf.py --project test --remote PRJEB14409 --clustering usearch_smallmem --classification silva --forward_primer CCTACGGGNGGCWGCAG --reverse_primer GACTACHVGGGTATCTAATCC --mergepairs vsearch --reference_db silva
    - snakemake  --use-conda -j 8
