image: continuumio/miniconda3

before_script:
  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda config --add channels r
  - conda config --add channels bioconda
  - conda install snakemake click

stages:
    - rulegraph
    - run
    
# DAG
#rulegraph:
#  stage: rulegraph
#  script: 
#    - snakemake --configfile tests/config.remote.yaml --rulegraph --use-conda

run:
  stage: run
  script:
    - python conf.py --project test --remote PRJEB14409
    - snakemake  --use-conda -j 8
